//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carti
    {
        public Carti()
        {
            this.DetaliiComenzis = new HashSet<DetaliiComenzi>();
            this.Autoris = new HashSet<Autori>();
        }
    
        public int CartiID { get; set; }
        public int FurnizorID { get; set; }
        public string NumeCarte { get; set; }
        public int UnitatiStoc { get; set; }
        public int UnitatiComandate { get; set; }
        public string PretUnitar { get; set; }
        public string Descriere { get; set; }
        public int EdituraID { get; set; }
    
        public virtual Edituri Edituri { get; set; }
        public virtual Furnizori Furnizori { get; set; }
        public virtual ICollection<DetaliiComenzi> DetaliiComenzis { get; set; }
        public virtual ICollection<Autori> Autoris { get; set; }
    }
}
