//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clienti
    {
        public Clienti()
        {
            this.Comenzis = new HashSet<Comenzi>();
        }
    
        public int ClientiID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public System.DateTime DataInregistrare { get; set; }
    
        public virtual ICollection<Comenzi> Comenzis { get; set; }
    }
}
