//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comenzi
    {
        public Comenzi()
        {
            this.DetaliiComenzis = new HashSet<DetaliiComenzi>();
        }
    
        public int ComenziID { get; set; }
        public int ClientiID { get; set; }
        public System.DateTime DataComanada { get; set; }
        public string Platit { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        public virtual ICollection<DetaliiComenzi> DetaliiComenzis { get; set; }
    }
}
