//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiComenzi
    {
        public int DetaliiComenziID { get; set; }
        public int CartiID { get; set; }
        public int ComenziID { get; set; }
        public int Cantitate { get; set; }
    
        public virtual Carti Carti { get; set; }
        public virtual Comenzi Comenzi { get; set; }
    }
}
