//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edituri
    {
        public Edituri()
        {
            this.Cartis = new HashSet<Carti>();
        }
    
        public int EdituraID { get; set; }
        public string NumeEditura { get; set; }
    
        public virtual ICollection<Carti> Cartis { get; set; }
    }
}
